import { defineMessages } from 'react-intl';

export default {
  counties: {
    values: [
      'Unknown',
      'Abbeville',
      'Aberdeenshire (UK)',
      'Acadia',
      'Acaponeta',
      'Accomack',
      'Ada',
      'Adair',
      'Adams',
      'Addison',
      'Agusan del Norte',
      'Ahuacatlan',
      'Aiken',
      'Aitkin',
      'Alachua',
      'Alamance',
      'Alameda',
      'Alamosa',
      'Albany',
      'Albemarle',
      'Alcona',
      'Alcorn',
      'Aleutians East',
      'Aleutians West',
      'Alexander',
      'Alexandria',
      'Alfalfa',
      'Alger',
      'Allamakee',
      'Allegan',
      'Allegany',
      'Alleghany',
      'Allegheny',
      'Allen',
      'Allendale',
      'Alpena',
      'Alpine',
      'Amador',
      'Amazonas',
      'Amelia',
      'Amherst',
      'Amite',
      'Anchorage',
      'Anderson',
      'Andrew',
      'Andrews',
      'Androscoggin',
      'Angelina',
      'Anglesey',
      'Anglesey (UK)',
      'Angus (Forfarshire) (UK)',
      'Anne Arundel',
      'Anoka',
      'Anson',
      'Antelope',
      'Antonina',
      'Antrim',
      'Antrim (UK)',
      'Apache',
      'Appanoose',
      'Appling',
      'Appomattox',
      'Aransas',
      'Arapahoe',
      'Archer',
      'Archuleta',
      'Arenac',
      'Argyll (Argyllshire) (UK)',
      'Arkansas',
      'Arlington',
      'Armagh (UK)',
      'Armstrong',
      'Aroostook',
      'Arran, Island of',
      'Arthur',
      'Ascension',
      'Ashe',
      'Ashland',
      'Ashley',
      'Ashtabula',
      'Asotin',
      'Assumption',
      'Atascosa',
      'Atchison',
      'Athens',
      'Atkinson',
      'Atlantic',
      'Atoka',
      'Attala',
      'Audrain',
      'Audubon',
      'Auglaize',
      'Augusta',
      'Aurora',
      'Austin',
      'Autauga',
      'Avery',
      'Avoyelles',
      'Ayopaya',
      'Ayrshire (UK)',
      'Ba',
      'Baca',
      'Bacon',
      'Bagua',
      'Bailey',
      'Baker',
      'Baldwin',
      'Ballard',
      'Baltimore',
      'Bamberg',
      'Bandera',
      'Banffshire (UK)',
      'Banks',
      'Banner',
      'Bannock',
      'Baraga',
      'Barber',
      'Barbour',
      'Barnes',
      'Barnstable',
      'Barnwell',
      'Barreiras',
      'Barren',
      'Barron',
      'Barrow',
      'Barry',
      'Bartholomew',
      'Barton',
      'Bartow',
      'Bastrop',
      'Bates',
      'Bath',
      'Baxter',
      'Bay',
      'Bayfield',
      'Baylor',
      'Beadle',
      'Bear Lake',
      'Beaufort',
      'Beauregard',
      'Beaver',
      'Beaverhead',
      'Becker',
      'Beckham',
      'Bedford',
      'Bedfordshire (UK)',
      'Bee',
      'Belknap',
      'Bell',
      'Belmont',
      'Beltrami',
      'Ben Hill',
      'Benewah',
      'Bennett',
      'Bennington',
      'Benson',
      'Bent',
      'Benton',
      'Benzie',
      'Bergen',
      'Berkeley',
      'Berks',
      'Berkshire',
      'Berkshire (UK)',
      'Bernalillo',
      'Berrien',
      'Bertie',
      'Berwickshire (UK)',
      'Bethel',
      'Bexar',
      'Bibb',
      'Bienville',
      'Big Horn',
      'Big Stone',
      'Billings',
      'Bingham',
      'Black Hawk',
      'Blackford',
      'Bladen',
      'Blaine',
      'Blair',
      'Blanco',
      'Bland',
      'Bleckley',
      'Bledsoe',
      'Blount',
      'Blue Earth',
      'Boise',
      'Bolivar',
      'Bollinger',
      'Bon Homme',
      'Bonaventure',
      'Bond',
      'Bongara',
      'Bonner',
      'Bonneville',
      'Boone',
      'Borden',
      'Bosque',
      'Bossier',
      'Botetourt',
      'Bothwell Municipality',
      'Bottineau',
      'Boulder',
      'Boundary',
      'Bourbon',
      'Bowie',
      'Bowman',
      'Box Butte',
      'Box Elder',
      'Boyd',
      'Boyle',
      'Bracken',
      'Bradford',
      'Bradley',
      'Branch',
      'Brantley',
      'Braxton',
      'Brazoria',
      'Brazos',
      'Breathitt',
      'Breckinridge',
      'Brecknockshire (Breconshire) (UK)',
      'Bremer',
      'Brevard',
      'Brewster',
      'Briscoe',
      'Bristol',
      'Bristol Bay',
      'Broadwater',
      'Bronx',
      'Brooke',
      'Brookings',
      'Brooks',
      'Broome',
      'Broomfield',
      'Broward',
      'Brown',
      'Brule',
      'Brunswick',
      'Bryan',
      'Buchanan',
      'Buckingham',
      'Buckinghamshire (UK)',
      'Bucks',
      'Buena Vista',
      'Buffalo',
      'Bullitt',
      'Bulloch',
      'Bullock',
      'Buncombe',
      'Bureau',
      'Burke',
      'Burleigh',
      'Burleson',
      'Burlington',
      'Burnet',
      'Burnett',
      'Burnie Municipality',
      'Burt',
      'Buteshire (UK)',
      'Butler',
      'Butte',
      'Butts',
      'Cabarrus',
      'Cabell',
      'Cache',
      'Caddo',
      'Caernarfonshire (Carnarvonshire) (UK)',
      'Caithness (UK)',
      'Cajamarca',
      'Calaveras',
      'Calcasieu',
      'Caldwell',
      'Caledonia',
      'Calhoun',
      'Callahan',
      'Callaway',
      'Calloway',
      'Calumet',
      'Calvert',
      'Camas',
      'Cambria',
      'Cambridgeshire (UK)',
      'Camden',
      'Cameron',
      'Camp',
      'Campbell',
      'Canadian',
      'Candelaria',
      'Candler',
      'Cannon',
      'Canyon',
      'Cape Girardeau',
      'Cape May',
      'Capiz',
      'Carangola',
      'Carbon',
      'Cardiganshire (UK)',
      'Caribou',
      'Carlisle',
      'Carlton',
      'Carmarthenshire (UK)',
      'Caroline',
      'Carroll',
      'Carson',
      'Carson City',
      'Carter',
      'Carteret',
      'Carver',
      'Cascade',
      'Casey',
      'Cass',
      'Cassia',
      'Castro',
      'Castrovirreina',
      'Caswell',
      'Catahoula',
      'Catawba',
      'Catoosa',
      'Catron',
      'Cattaraugus',
      'Cautin',
      'Cavalier',
      'Cayuga',
      'Cecil',
      'Cedar',
      'Celendin',
      'Centre',
      'Cerro Gordo',
      'Chachapoyas',
      'Chaffee',
      'Chambers',
      'Champaign',
      'Chariton',
      'Charles',
      'Charles City',
      'Charles Mix',
      'Charleston',
      'Charlevoix',
      'Charlotte',
      'Charlottesville',
      'Charlton',
      'Chase',
      'Chatham',
      'Chattahoochee',
      'Chattooga',
      'Chautauqua',
      'Chaves',
      'Cheatham',
      'Cheboygan',
      'Chelan',
      'Chemung',
      'Chenango',
      'Cherokee',
      'Cherry',
      'Chesapeake',
      'Cheshire',
      'Cheshire (UK)',
      'Chester',
      'Chesterfield',
      'Cheyenne',
      'Chiang Mai, Changwat',
      'Chickasaw',
      'Chicligasta',
      'Chicot',
      'Childress',
      'Chilton',
      'Chippewa',
      'Chisago',
      'Chittenden',
      'Choctaw',
      'Chouteau',
      'Chowan',
      'Christian',
      'Churchill',
      'Cibola',
      'Cimarron',
      'Citrus',
      'Clackamas',
      'Clackmannanshire (UK)',
      'Claiborne',
      'Clallam',
      'Clare',
      'Clarendon',
      'Clarion',
      'Clark',
      'Clarke',
      'Clatsop',
      'Clay',
      'Clayton',
      'Clear Creek',
      'Clearfield',
      'Clearwater',
      'Cleburne',
      'Clermont',
      'Cleveland',
      'Clinch',
      'Clinton',
      'Cloud',
      'Coahoma',
      'Coal',
      'Cobb',
      'Cochise',
      'Cochran',
      'Cocke',
      'Coconino',
      'Codington',
      'Coffee',
      'Coffey',
      'Coke',
      'Colbert',
      'Cole',
      'Coleman',
      'Coles',
      'Colfax',
      'Colleton',
      'Collier',
      'Collin',
      'Collingsworth',
      'Colonial Heights',
      'Colorado',
      'Colquitt',
      'Columbia',
      'Columbiana',
      'Columbus',
      'Colusa',
      'Comal',
      'Comanche',
      'Comondú',
      'Compostela',
      'Concho',
      'Concordia',
      'Conecuh',
      'Conejos',
      'Contra Costa',
      'Converse',
      'Conway',
      'Cook',
      'Cooke',
      'Cooper',
      'Coos',
      'Coosa',
      'Copiah',
      'Cornwall',
      'Cornwall (UK)',
      'Corson',
      'Cortland',
      'Corumba',
      'Coryell',
      'Coshocton',
      'Costilla',
      'Cottle',
      'Cotton',
      'Cottonwood',
      'Covington',
      'Coweta',
      'Cowley',
      'Cowlitz',
      'Craig',
      'Craighead',
      'Crane',
      'Craven',
      'Crawford',
      'Creek',
      'Crenshaw',
      'Crisp',
      'Crittenden',
      'Crockett',
      'Cromartyshire (UK)',
      'Crook',
      'Crosby',
      'Cross',
      'Crow Wing',
      'Crowley',
      'Culberson',
      'Cullman',
      'Culpeper',
      'Cumberland',
      'Cumberland (UK)',
      'Cuming',
      'Currituck',
      'Curry',
      'Custer',
      'Cuyahoga',
      'Dade',
      'Daggett',
      'Dakota',
      'Dale',
      'Dallam',
      'Dallas',
      'Dane',
      'Daniels',
      'Danville',
      'Dare',
      'Darke',
      'Darlington',
      'Dauphin',
      'Davidson',
      'Davie',
      'Daviess',
      'Davis',
      'Davison',
      'Dawes',
      'Dawson',
      'Day',
      'De Baca',
      'De Kalb',
      'De Soto',
      'De Witt',
      'Deaf Smith',
      'Dearborn',
      'Decatur',
      'Deer Lodge',
      'Defiance',
      'DeKalb',
      'Del Norte',
      'Delaware',
      'Deloraine Municipality',
      'Delta',
      'Denali',
      'Denbighshire (UK)',
      'Dent',
      'Denton',
      'Denver',
      'Derbyshire (UK)',
      'Des Moines',
      'Deschutes',
      'Desha',
      'DeSoto',
      'Deuel',
      'Devon (UK)',
      'Dewey',
      'DeWitt',
      'Diamantina',
      'Dickens',
      'Dickenson',
      'Dickey',
      'Dickinson',
      'Dickson',
      'Dillingham',
      'Dillon',
      'Dimmit',
      'Dinwiddie',
      'District of Columbia',
      'Divide',
      'Dixie',
      'Dixon',
      'Doddridge',
      'Dodge',
      'Dolores',
      'Dona Ana',
      'Doniphan',
      'Donley',
      'Dooly',
      'Door',
      'Dorchester',
      'Dorset (UK)',
      'Dougherty',
      'Douglas',
      'Down (UK)',
      'Doña Ana',
      'Drew',
      'Du Page',
      'Dubois',
      'Dubuque',
      'Duchesne',
      'Dukes',
      'Dumbartonshire (UK)',
      'Dumfriesshire (UK)',
      'Dundy',
      'Dunklin',
      'Dunn',
      'DuPage',
      'Duplin',
      'Durham',
      'Durham (UK)',
      'Dutchess',
      'Duval',
      'Dyer',
      'Eagle',
      'Early',
      'East Baton Rouge',
      'East Carroll',
      'East Feliciana',
      'East Lothian (UK)',
      'Eastland',
      'Eaton',
      'Eau Claire',
      'Echols',
      'Ector',
      'Eddy',
      'Edgar',
      'Edgecombe',
      'Edgefield',
      'Edmonson',
      'Edmunds',
      'Edwards',
      'Effingham',
      'El Dorado',
      'El Paso',
      'Elbert',
      'Elk',
      'Elkhart',
      'Elko',
      'Elliott',
      'Ellis',
      'Ellsworth',
      'Elmore',
      'Emanuel',
      'Emery',
      'Emmet',
      'Emmons',
      'Emporia',
      'Ensenada',
      'Erath',
      'Erie',
      'Escambia',
      'Esmeralda',
      'Esmeraldas',
      'Esperance Municipality',
      'Essex',
      'Essex (MA)',
      'Essex (UK)',
      'Estill',
      'Etowah',
      'Eureka',
      'Evangeline',
      'Evans',
      'Fairbanks North Star',
      'Fairfax',
      'Fairfield',
      'Fall River',
      'Fallon',
      'Falls',
      'Falls Church',
      'Fannin',
      'Faribault',
      'Faulk',
      'Faulkner',
      'Fauquier',
      'Fayette',
      'Fentress',
      'Fergus',
      'Fermanagh (UK)',
      'Ferry',
      'Fife (UK)',
      'Fillmore',
      'Fingal Municipality',
      'Finney',
      'Fisher',
      'Flagler',
      'Flathead',
      'Fleming',
      'Flintshire (UK)',
      'Florence',
      'Florida',
      'Floyd',
      'Fluvanna',
      'Foard',
      'Fond Du Lac',
      'Fond du Lac',
      'Ford',
      'Forest',
      'Forrest',
      'Forsyth',
      'Fort Bend',
      'Foster',
      'Fountain',
      'Franklin',
      'Frederick',
      'Fredericksburg',
      'Freeborn',
      'Freestone',
      'Fremont',
      'Fresno',
      'Frio',
      'Frontier',
      'Fulton',
      'Furnas',
      'Gadsden',
      'Gage',
      'Gaines',
      'Galapagos',
      'Galax',
      'Gallatin',
      'Gallia',
      'Galveston',
      'Galway',
      'Garden',
      'Garfield',
      'Garland',
      'Garrard',
      'Garrett',
      'Garvin',
      'Garza',
      'Gasconade',
      'Gaston',
      'Gates',
      'Geary',
      'Geauga',
      'Gem',
      'Genesee',
      'Geneva',
      'Gentry',
      'George',
      'Georgetown',
      'Gibson',
      'Gila',
      'Gilchrist',
      'Giles',
      'Gillespie',
      'Gilliam',
      'Gilmer',
      'Gilpin',
      'Glacier',
      'Glades',
      'Gladwin',
      'Glamorgan (UK)',
      'Glamorgan Municipality',
      'Glascock',
      'Glasscock',
      'Glenn',
      'Glenorchy Municipality',
      'Gloucester',
      'Gloucestershire (UK)',
      'Glynn',
      'Gogebic',
      'Golden Valley',
      'Goliad',
      'Gonzales',
      'Goochland',
      'Goodhue',
      'Gooding',
      'Gordon',
      'Gormanston Municipality',
      'Goshen',
      'Gosper',
      'Gouveia',
      'Gove',
      'Grady',
      'Grafton',
      'Graham',
      'Grainger',
      'Grand',
      'Grand Forks',
      'Grand Isle',
      'Grand Traverse',
      'Granite',
      'Grant',
      'Granville',
      'Gratiot',
      'Graves',
      'Gray',
      'Grays Harbor',
      'Grayson',
      'Greeley',
      'Green',
      'Green Lake',
      'Greenbrier',
      'Greene',
      'Greenlee',
      'Greensville',
      'Greenup',
      'Greenville',
      'Greenwood',
      'Greer',
      'Gregg',
      'Gregory',
      'Grenada',
      'Griggs',
      'Grimes',
      'Grundy',
      'Guadalupe',
      'Guaraquecaba',
      'Guaratuba',
      'Guernsey',
      'Guilford',
      'Gulf',
      'Gunnison',
      'Guthrie',
      'Gwinnett',
      'Haakon',
      'Habersham',
      'Haines',
      'Hale',
      'Halifax',
      'Hall',
      'Hamblen',
      'Hamilton',
      'Hamilton Municipality',
      'Hamlin',
      'Hampden',
      'Hampshire',
      'Hampshire (UK)',
      'Hampton',
      'Hancock',
      'Hand',
      'Hanover',
      'Hansford',
      'Hanson',
      'Haralson',
      'Hardee',
      'Hardeman',
      'Hardin',
      'Harding',
      'Hardy',
      'Harford',
      'Harlan',
      'Harmon',
      'Harnett',
      'Harney',
      'Harper',
      'Harris',
      'Harrison',
      'Harrisonburg',
      'Hart',
      'Hartford',
      'Hartley',
      'Harvey',
      'Haskell',
      'Hawaii',
      'Hawkins',
      'Hayes',
      'Hays',
      'Haywood',
      'Heard',
      'Hemphill',
      'Hempstead',
      'Henderson',
      'Hendricks',
      'Hendry',
      'Hennepin',
      'Henrico',
      'Henry',
      'Herefordshire (UK)',
      'Herkimer',
      'Hernando',
      'Hertford',
      'Hertfordshire (UK)',
      'Hettinger',
      'Hickman',
      'Hickory',
      'Hidalgo',
      'Highland',
      'Highlands',
      'Hill',
      'Hillsborough',
      'Hillsdale',
      'Hinds',
      'Hinsdale',
      'Hitchcock',
      'Hobart Municipality',
      'Hocking',
      'Hockley',
      'Hodgeman',
      'Hoke',
      'Holmes',
      'Holt',
      'Honolulu',
      'Hood',
      'Hood River',
      'Hooker',
      'Hoonah–Angoon',
      'Hopewell',
      'Hopkins',
      'Horry',
      'Hot Spring',
      'Hot Springs',
      'Houghton',
      'Houston',
      'Howard',
      'Howell',
      'Huancabamba',
      'Huanuco',
      'Hubbard',
      'Hudson',
      'Hudspeth',
      'Huerfano',
      'Hughes',
      'Humboldt',
      'Humphreys',
      'Hunt',
      'Hunterdon',
      'Huntingdon',
      'Huntingdonshire (UK)',
      'Huntington',
      'Huron',
      'Hutchinson',
      'Hyde',
      'Iberia',
      'Iberville',
      'Ida',
      'Idaho',
      'Imperial',
      'Independence',
      'Indian River',
      'Indiana',
      'Ingham',
      'Inverness-shire (UK)',
      'Inyo',
      'Ionia',
      'Iosco',
      'Iowa',
      'Iredell',
      'Irion',
      'Iron',
      'Iroquois',
      'Irwin',
      'Isabella',
      'Isanti',
      'Island',
      'Isle of Wight',
      'Issaquena',
      'Itasca',
      'Itawamba',
      'Ixtlan',
      'Izard',
      'Jack',
      'Jackson',
      'Jaguariaiya',
      'Jalisco',
      'James City',
      'Jasper',
      'Jay',
      'Jeff Davis',
      'Jefferson',
      'Jefferson Davis',
      'Jenkins',
      'Jennings',
      'Jerauld',
      'Jerome',
      'Jersey',
      'Jessamine',
      'Jewell',
      'Jim Hogg',
      'Jim Wells',
      'Jo Daviess',
      'Johnson',
      'Johnston',
      'Jolo Group',
      'Jones',
      'Josephine',
      'Juab',
      'Judith Basin',
      'Juneau',
      'Juniata',
      'Juquila',
      'Kalamazoo',
      'Kalawao',
      'Kalkaska',
      'Kanabec',
      'Kanawha',
      'Kandavu',
      'Kandiyohi',
      'Kane',
      'Kankakee',
      'Karnes',
      'Kauai',
      'Kaufman',
      'Kay',
      'Kearney',
      'Kearny',
      'Keith',
      'Kemper',
      'Kenai Peninsula',
      'Kendall',
      'Kenedy',
      'Kennebec',
      'Kenosha',
      'Kent',
      'Kent (UK)',
      'Kentish Municipality',
      'Kenton',
      'Keokuk',
      'Kepulauan',
      'Kepulauan Kangean Islands',
      'Kern',
      'Kerr',
      'Kershaw',
      'Ketchikan Gateway',
      'Kewaunee',
      'Keweenaw',
      'Keya Paha',
      'Kidder',
      'Kimball',
      'Kimble',
      'Kincardineshire (UK)',
      'King',
      'King and Queen',
      'King George',
      'King William',
      'Kingborough Municipality',
      'Kingfisher',
      'Kingman',
      'Kings',
      'Kingsbury',
      'Kinney',
      'Kinross-shire (UK)',
      'Kiowa',
      'Kirkcudbrightshire (UK)',
      'Kit Carson',
      'Kitsap',
      'Kittitas',
      'Kittson',
      'Klamath',
      'Kleberg',
      'Klickitat',
      'Knott',
      'Knox',
      'Kodiak Island',
      'Koochiching',
      'Kootenai',
      'Korinthos',
      'Koro',
      'Kosciusko',
      'Kossuth',
      'La Crosse',
      'La Paz',
      'La Plata',
      'La Salle',
      'Labette',
      'Lac qui Parle',
      'Lackawanna',
      'Laclede',
      'Lafayette',
      'Lafourche',
      'LaGrange',
      'Lake',
      'Lake and Peninsula',
      'Lake of the Woods',
      'Lamar',
      'Lamas',
      'Lamb',
      'Lamoille',
      'LaMoure',
      'Lampasas',
      'Lanarkshire (UK)',
      'Lancashire (UK)',
      'Lancaster',
      'Lander',
      'Lane',
      'Langlade',
      'Lanier',
      'Lapeer',
      'LaPorte',
      'Laramie',
      'Larecaja',
      'Larimer',
      'LaRue',
      'Las Animas',
      'LaSalle',
      'Lassen',
      'Latah',
      'Latimer',
      'Lauderdale',
      'Launceston Municipality',
      'Laurel',
      'Laurens',
      'Lavaca',
      'Lawrence',
      'Le Flore',
      'Le Sueur',
      'Lea',
      'Leake',
      'Leavenworth',
      'Lebanon',
      'Lee',
      'Leelanau',
      'Leflore',
      'Lehigh',
      'Leicestershire (UK)',
      'Lemhi',
      'Lenawee',
      'Lenoir',
      'Leon',
      'Leslie',
      'Letcher',
      'Levy',
      'Lewis',
      'Lewis and Clark',
      'Lexington',
      'Liberty',
      'Licking',
      'Lilydale Municipality',
      'Limestone',
      'Lincoln',
      'Lincolnshire (UK)',
      'Linn',
      'Lipscomb',
      'Litchfield',
      'Little River',
      'Live Oak',
      'Livingston',
      'Llano',
      'Logan',
      'Loja',
      'Londonderry (UK)',
      'Long',
      'Longford Municipality',
      'Lonoke',
      'Lorain',
      'Loreto',
      'Los Alamos',
      'Los Angeles',
      'Los Cabos',
      'Loudon',
      'Loudoun',
      'Louisa',
      'Loup',
      'Love',
      'Loving',
      'Lowndes',
      'Lubbock',
      'Lucas',
      'Luce',
      'Lumpkin',
      'Luna',
      'Lunenburg',
      'Luzerne',
      'Lycoming',
      'Lyman',
      'Lynchburg',
      'Lynn',
      'Lyon',
      'Mackinac',
      'Macomb',
      'Macon',
      'Macoupin',
      'Madera',
      'Madison',
      'Magoffin',
      'Mahaska',
      'Mahnomen',
      'Mahoning',
      'Major',
      'Malheur',
      'Manabi',
      'Manassas',
      'Manassas Park',
      'Manatee',
      'Manistee',
      'Manitowoc',
      'Marathon',
      'Marengo',
      'Maricopa',
      'Maries',
      'Marin',
      'Marinette',
      'Marion',
      'Mariposa',
      'Marlboro',
      'Marquette',
      'Marshall',
      'Martin',
      'Martinsville',
      'Mason',
      'Massac',
      'Matagorda',
      'Matanuska-Susitna',
      'Mathews',
      'Maui',
      'Maury',
      'Maverick',
      'Mayes',
      'McClain',
      'McCone',
      'McCook',
      'McCormick',
      'McCracken',
      'McCreary',
      'McCulloch',
      'McCurtain',
      'McDonald',
      'McDonough',
      'McDowell',
      'McDuffie',
      'McHenry',
      'McIntosh',
      'McKean',
      'McKenzie',
      'McKinley',
      'McLean',
      'McLennan',
      'McLeod',
      'McMinn',
      'McMullen',
      'McNairy',
      'McPherson',
      'Meade',
      'Meagher',
      'Mecklenburg',
      'Mecosta',
      'Medina',
      'Meeker',
      'Meigs',
      'Mellette',
      'Menard',
      'Mendocino',
      'Menifee',
      'Menominee',
      'Merced',
      'Mercer',
      'Merionethshire (UK)',
      'Meriwether',
      'Merrick',
      'Merrimack',
      'Mesa',
      'Metcalfe',
      'Mexicali',
      'Miahuatlan',
      'Miami',
      'Miami-Dade',
      'Middlesex',
      'Middlesex (UK)',
      'Midland',
      'Midlothian (UK)',
      'Mifflin',
      'Milam',
      'Millard',
      'Mille Lacs',
      'Miller',
      'Mills',
      'Milwaukee',
      'Miner',
      'Mineral',
      'Mingo',
      'Minidoka',
      'Minnehaha',
      'Missaukee',
      'Mississippi',
      'Missoula',
      'Mitchell',
      'Mizque',
      'Mobile',
      'Modoc',
      'Moffat',
      'Mohave',
      'Moniteau',
      'Monmouth',
      'Monmouthshire (UK)',
      'Mono',
      'Monona',
      'Monongalia',
      'Monroe',
      'Montague',
      'Montcalm',
      'Monterey',
      'Montezuma',
      'Montgomery',
      'Montgomeryshire (UK)',
      'Montmorency',
      'Montour',
      'Montrose',
      'Moody',
      'Moore',
      'Mora',
      'Morayshire (UK)',
      'Morehouse',
      'Morgan',
      'Morrill',
      'Morris',
      'Morrison',
      'Morro do Chapeu',
      'Morrow',
      'Morton',
      'Motley',
      'Moultrie',
      'Mountrail',
      'Mower',
      'Muhlenberg',
      'Mulegé',
      'Multnomah',
      'Murray',
      'Muscatine',
      'Muscogee',
      'Muskegon',
      'Muskingum',
      'Muskogee',
      'Musselshell',
      'Nacogdoches',
      'Nairnshire (UK)',
      'Nakhon Ratchasima, Changwat',
      'Nance',
      'Nantucket',
      'Nantucket (MA)',
      'Napa',
      'Nash',
      'Nassau',
      'Natchitoches',
      'Natrona',
      'Navajo',
      'Navarro',
      'Nelson',
      'Nemaha',
      'Neosho',
      'Neshoba',
      'Ness',
      'Nevada',
      'New Castle',
      'New Hanover',
      'New Haven',
      'New Kent',
      'New London',
      'New Madrid',
      'New Norfolk Municipality',
      'New York',
      'Newaygo',
      'Newberry',
      'Newport',
      'Newport News',
      'Newton',
      'Nez Perc',
      'Nez Perce',
      'Niagara',
      'Nicholas',
      'Nicholson',
      'Nicollet',
      'Niobrara',
      'Noble',
      'Nobles',
      'Nodaway',
      'Nolan',
      'Nome',
      'Norfolk',
      'Norfolk (UK)',
      'Norman',
      'North Slope',
      'Northampton',
      'Northamptonshire (UK)',
      'Northumberland',
      'Northumberland (UK)',
      'Northwest Arctic',
      'Norton',
      'Nottinghamshire (UK)',
      'Nottoway',
      'Nowata',
      'Noxubee',
      'Nuckolls',
      'Nueces',
      'Nueva Vizcaya',
      'Nye',
      'O\'Brien',
      'Oakland',
      'Oatlands Municipality',
      'Obion',
      'Ocean',
      'Oceana',
      'Ochiltree',
      'Oconee',
      'Oconto',
      'Ogemaw',
      'Ogle',
      'Oglethorpe',
      'Ohio',
      'Okaloosa',
      'Okanogan',
      'Okeechobee',
      'Okfuskee',
      'Oklahoma',
      'Okmulgee',
      'Oktibbeha',
      'Oldham',
      'Oliver',
      'Olmsted',
      'Oneida',
      'Onondaga',
      'Onslow',
      'Ontario',
      'Ontonagon',
      'Orange',
      'Orangeburg',
      'Oregon',
      'Orkney (UK)',
      'Orleans',
      'Osage',
      'Osborne',
      'Osceola',
      'Oscoda',
      'Oswego',
      'Otero',
      'Otoe',
      'Otsego',
      'Ottawa',
      'Otter Tail',
      'Ouachita',
      'Ouray',
      'Outagamie',
      'Overton',
      'Owen',
      'Owsley',
      'Owyhee',
      'Oxford',
      'Oxfordshire (UK)',
      'Ozark',
      'Ozaukee',
      'Pacific',
      'Page',
      'Palm Beach',
      'Palmeira',
      'Palo Alto',
      'Palo Pinto',
      'Pamlico',
      'Pampanga',
      'Pangasinan',
      'Panola',
      'Paranagua',
      'Park',
      'Parke',
      'Parker',
      'Parmer',
      'Pasco',
      'Pasquotank',
      'Passaic',
      'Patrick',
      'Paulding',
      'Pawnee',
      'Payette',
      'Payne',
      'Peach',
      'Pearl River',
      'Pecos',
      'Peeblesshire (UK)',
      'Pembina',
      'Pembrokeshire (UK)',
      'Pemiscot',
      'Pend Oreille',
      'Pender',
      'Pendleton',
      'Penguin Municipality',
      'Pennington',
      'Penobscot',
      'Peoria',
      'Pepin',
      'Perkins',
      'Perquimans',
      'Perry',
      'Pershing',
      'Person',
      'Perthshire (UK)',
      'Petersburg',
      'Petroleum',
      'Pettis',
      'Phelps',
      'Philadelphia',
      'Phillips',
      'Piatt',
      'Pickaway',
      'Pickens',
      'Pickett',
      'Pierce',
      'Pike',
      'Pima',
      'Pinal',
      'Pine',
      'Pinellas',
      'Pipestone',
      'Piscataquis',
      'Pitkin',
      'Pitt',
      'Pittsburg',
      'Pittsylvania',
      'Piura',
      'Piute',
      'Placer',
      'Plaquemines',
      'Platte',
      'Pleasants',
      'Plumas',
      'Plymouth',
      'Pocahontas',
      'Pochutla',
      'Poinsett',
      'Pointe Coupee',
      'Polk',
      'Pondera',
      'Pontotoc',
      'Pope',
      'Poquoson',
      'Portage',
      'Porter',
      'Portland Municipality',
      'Portsmouth',
      'Posey',
      'Pottawatomie',
      'Pottawattamie',
      'Potter',
      'Powder River',
      'Powell',
      'Power',
      'Poweshiek',
      'Powhatan',
      'Prairie',
      'Pratt',
      'Preble',
      'Prentiss',
      'Presidio',
      'Presque Isle',
      'Preston',
      'Price',
      'Prince Edward',
      'Prince George',
      'Prince George\'s',
      'Prince of Wales-Hyder',
      'Prince William',
      'Providence',
      'Prowers',
      'Pueblo',
      'Pujili',
      'Pulaski',
      'Pushmataha',
      'Putnam',
      'Quay',
      'Queen Anne\'s',
      'Queen Elizabeth Islands',
      'Queens',
      'Quezon',
      'Quitman',
      'Quito',
      'Rabun',
      'Racine',
      'Radford',
      'Radnorshire (UK)',
      'Raiatea',
      'Rains',
      'Raleigh',
      'Ralls',
      'Ramsey',
      'Randall',
      'Randolph',
      'Rankin',
      'Ransom',
      'Rapides',
      'Rappahannock',
      'Rarotonga',
      'Ravalli',
      'Rawlins',
      'Ray',
      'Reagan',
      'Real',
      'Red Lake',
      'Red River',
      'Red Willow',
      'Redwood',
      'Reeves',
      'Refugio',
      'Renfrewshire (UK)',
      'Reno',
      'Rensselaer',
      'Renville',
      'Republic',
      'Rewa',
      'Reynolds',
      'Rhea',
      'Rice',
      'Rich',
      'Richardson',
      'Richland',
      'Richmond',
      'Riley',
      'Ringarooma Municipality',
      'Ringgold',
      'Rio Arriba',
      'Rio Blanco',
      'Rio Branco',
      'Rio Grande',
      'Rio Verde',
      'Ripley',
      'Ritchie',
      'Riverside',
      'Rizal',
      'Roane',
      'Roanoke',
      'Roberts',
      'Robertson',
      'Robeson',
      'Rock',
      'Rock Island',
      'Rockbridge',
      'Rockcastle',
      'Rockdale',
      'Rockingham',
      'Rockland',
      'Rockwall',
      'Roger Mills',
      'Rogers',
      'Rolette',
      'Rooks',
      'Roosevelt',
      'Rosarito, Playas de',
      'Roscommon',
      'Roseau',
      'Rosebud',
      'Ross',
      'Ross Municipality',
      'Ross-shire (UK)',
      'Routt',
      'Rowan',
      'Roxburghshire (UK)',
      'Runnels',
      'Rush',
      'Rusk',
      'Russell',
      'Russell Islands',
      'Rutherford',
      'Rutland',
      'Rutland (UK)',
      'Sabah',
      'Sabine',
      'Sac',
      'Sacramento',
      'Sagadahoc',
      'Saginaw',
      'Saguache',
      'Salem',
      'Saline',
      'Salt Lake',
      'Saluda',
      'Sampson',
      'San Augustine',
      'San Benito',
      'San Bernardino',
      'San Blas',
      'San Diego',
      'San Francisco',
      'San Ignacio',
      'San Jacinto',
      'San Joaquin',
      'San Juan',
      'San Luis Obispo',
      'San Mateo',
      'San Miguel',
      'San Patricio',
      'San Pedro Lagunillas',
      'San Pedro Lagunitas',
      'San Saba',
      'Sanborn',
      'Sanders',
      'Sandoval',
      'Sandusky',
      'Sangamon',
      'Sanilac',
      'Sanpete',
      'Santa Barbara',
      'Santa Clara',
      'Santa Cruz',
      'Santa Fe',
      'Santa Maria del Oro',
      'Santa Rosa',
      'Santa Victoria',
      'Sarasota',
      'Saratoga',
      'Sarawak',
      'Sargent',
      'Sarpy',
      'Sauk',
      'Saunders',
      'Sawyer',
      'Schenectady',
      'Schleicher',
      'Schley',
      'Schoharie',
      'Schoolcraft',
      'Schuyler',
      'Schuylkill',
      'Scioto',
      'Scotland',
      'Scott',
      'Scotts Bluff',
      'Scottsdale Municipality',
      'Screven',
      'Scurry',
      'Searcy',
      'Sebastian',
      'Sedgwick',
      'Selkirkshire (UK)',
      'Seminole',
      'Seneca',
      'Senyavin Islands',
      'Sequatchie',
      'Sequoyah',
      'Sevier',
      'Seward',
      'Shackelford',
      'Shannon',
      'Sharkey',
      'Sharp',
      'Shasta',
      'Shawano',
      'Shawnee',
      'Sheboygan',
      'Sheffield Municipality',
      'Shelby',
      'Shenandoah',
      'Sherburne',
      'Sheridan',
      'Sherman',
      'Shetland (UK)',
      'Shiawassee',
      'Shoshone',
      'Shropshire (UK)',
      'Sibley',
      'Sierra',
      'Silver Bow',
      'Simpson',
      'Sioux',
      'Siskiyou',
      'Sitka',
      'Skagit',
      'Skagway',
      'Skamania',
      'Slope',
      'Smith',
      'Smyth',
      'Snohomish',
      'Snyder',
      'Socorro',
      'Sola de Vega',
      'Solano',
      'Somerset',
      'Somerset (UK)',
      'Somervell',
      'Sonoma',
      'Sorell Municipality',
      'Southampton',
      'Southeast Fairbanks',
      'Spalding',
      'Spartanburg',
      'Spencer',
      'Spink',
      'Spokane',
      'Spotsylvania',
      'Spring Bay Municipality',
      'St. Bernard',
      'St. Charles',
      'St. Clair',
      'St. Croix',
      'St. Francis',
      'St. Francois',
      'St. Helena',
      'St. James',
      'St. John the Baptist',
      'St. Johns',
      'St. Joseph',
      'St. Landry',
      'St. Lawrence',
      'St. Leonards Municipality',
      'St. Louis',
      'St. Lucie',
      'St. Martin',
      'St. Mary',
      'St. Mary\'s',
      'St. Tammany',
      'Stafford',
      'Staffordshire (UK)',
      'Stanislaus',
      'Stanley',
      'Stanly',
      'Stanton',
      'Stark',
      'Starke',
      'Starr',
      'Staunton',
      'Ste. Genevieve',
      'Stearns',
      'Steele',
      'Stephens',
      'Stephenson',
      'Sterling',
      'Steuben',
      'Stevens',
      'Stewart',
      'Stillwater',
      'Stirlingshire (UK)',
      'Stoddard',
      'Stokes',
      'Stone',
      'Stonewall',
      'Storey',
      'Story',
      'Strafford',
      'Stutsman',
      'Sublette',
      'Sud Yungas',
      'Suffolk',
      'Suffolk (UK)',
      'Sullivan',
      'Sully',
      'Summers',
      'Summit',
      'Sumner',
      'Sumter',
      'Sunflower',
      'Surrey (UK)',
      'Surry',
      'Susquehanna',
      'Sussex',
      'Sussex (UK)',
      'Sutherland (UK)',
      'Sutter',
      'Sutton',
      'Suwannee',
      'Swain',
      'Sweet Grass',
      'Sweetwater',
      'Swift',
      'Swisher',
      'Switzerland',
      'Tahiti',
      'Talbot',
      'Taliaferro',
      'Talladega',
      'Tallahatchie',
      'Tallapoosa',
      'Taltal',
      'Tama',
      'Taney',
      'Tangipahoa',
      'Taos',
      'Tarrant',
      'Tasman Municipality',
      'Tate',
      'Tattnall',
      'Taylor',
      'Tazewell',
      'Tecate',
      'Tehama',
      'Telfair',
      'Teller',
      'Tensas',
      'Tepic',
      'Terrebonne',
      'Terrell',
      'Terry',
      'Teton',
      'Texas',
      'Thayer',
      'Thomas',
      'Throckmorton',
      'Thurston',
      'Tift',
      'Tijuana',
      'Tillamook',
      'Tillman',
      'Tioga',
      'Tippah',
      'Tippecanoe',
      'Tipton',
      'Tishomingo',
      'Titus',
      'Todd',
      'Tolland',
      'Tom Green',
      'Tompkins',
      'Tompkins (NY)',
      'Tooele',
      'Toole',
      'Toombs',
      'Torrance',
      'Towner',
      'Towns',
      'Traill',
      'Transylvania',
      'Traverse',
      'Travis',
      'Treasure',
      'Trego',
      'Trempealeau',
      'Treutlen',
      'Trigg',
      'Trimble',
      'Trinity',
      'Tripp',
      'Troup',
      'Trousdale',
      'Trumbull',
      'Tucker',
      'Tulare',
      'Tulsa',
      'Tunica',
      'Tuolumne',
      'Turner',
      'Tuscaloosa',
      'Tuscarawas',
      'Tuscola',
      'Twiggs',
      'Twin Falls',
      'Tyler',
      'Tyrone (UK)',
      'Tyrrell',
      'Uinta',
      'Uintah',
      'Ulster',
      'Ulverstone Municipality',
      'Umatilla',
      'Unicoi',
      'Union',
      'Unknown',
      'Upshur',
      'Upson',
      'Upton',
      'Urubamba',
      'Utah',
      'Uvalde',
      'Val Verde',
      'Valdez–Cordova',
      'Valencia',
      'Valley',
      'Van Buren',
      'Van Wert',
      'Van Zandt',
      'Vance',
      'Vanderburgh',
      'Vanua Levu',
      'Venango',
      'Ventura',
      'Vermilion',
      'Vermillion',
      'Vernon',
      'Victoria',
      'Vigo',
      'Vilas',
      'Vinton',
      'Virginia Beach',
      'Viti Levu',
      'Volusia',
      'Wabash',
      'Wabasha',
      'Wabaunsee',
      'Wade Hampton',
      'Wadena',
      'Wagoner',
      'Wahkiakum',
      'Wake',
      'Wakulla',
      'Waldo',
      'Walker',
      'Walla Walla',
      'Wallace',
      'Waller',
      'Wallowa',
      'Walsh',
      'Walthall',
      'Walton',
      'Walworth',
      'Wapello',
      'Waratah Municipality',
      'Ward',
      'Ware',
      'Warren',
      'Warrick',
      'Warwickshire (UK)',
      'Wasatch',
      'Wasco',
      'Waseca',
      'Washakie',
      'Washburn',
      'Washington',
      'Washita',
      'Washoe',
      'Washtenaw',
      'Watauga',
      'Watonwan',
      'Waukesha',
      'Waupaca',
      'Waushara',
      'Wayne',
      'Waynesboro',
      'Weakley',
      'Webb',
      'Weber',
      'Webster',
      'Weld',
      'Wells',
      'West Baton Rouge',
      'West Carroll',
      'West Feliciana',
      'West Lothian (Linlithgowshire) (UK)',
      'Westchester',
      'Westmoreland',
      'Westmorland (UK)',
      'Weston',
      'Wetzel',
      'Wexford',
      'Wharton',
      'Whatcom',
      'Wheatland',
      'Wheeler',
      'White',
      'White Pine',
      'Whiteside',
      'Whitfield',
      'Whitley',
      'Whitman',
      'Wibaux',
      'Wichita',
      'Wicomico',
      'Wigtownshire (UK)',
      'Wilbarger',
      'Wilcox',
      'Wilkes',
      'Wilkin',
      'Wilkinson',
      'Will',
      'Will (IL)',
      'Willacy',
      'Williams',
      'Williamsburg',
      'Williamson',
      'Wilson',
      'Wiltshire (UK)',
      'Winchester',
      'Windham',
      'Windsor',
      'Winkler',
      'Winn',
      'Winnebago',
      'Winneshiek',
      'Winona',
      'Winston',
      'Wirt',
      'Wise',
      'Wolfe',
      'Wood',
      'Woodbury',
      'Woodford',
      'Woodruff',
      'Woods',
      'Woodson',
      'Woodward',
      'Worcester',
      'Worcestershire (UK)',
      'Worth',
      'Wrangell',
      'Wright',
      'Wyandot',
      'Wyandotte',
      'Wyoming',
      'Wythe',
      'Yadkin',
      'Yakima',
      'Yakutat',
      'Yalobusha',
      'Yamhill',
      'Yancey',
      'Yankton',
      'Yates',
      'Yavapai',
      'Yazoo',
      'Yell',
      'Yellow Medicine',
      'Yellowstone',
      'Yoakum',
      'Yolo',
      'York',
      'Yorkshire (UK)',
      'Young',
      'Yuba',
      'Yukon–Koyukuk',
      'Yuma',
      'Zambales',
      'Zapata',
      'Zavala',
      'Zeehan Municipality',
      'Zhongdian',
      'Ziebach',
    ],
    messages: defineMessages({
      Unknown: {
        id: 'option.counties.Unknown',
        defaultMessage: 'unknown',
      },
    }),
  },
  states: {
    values: [
      'Unknown',
      '\'Eua',
      'Aamzonas',
      'Acre',
      'AK',
      'AL',
      'Alajuela',
      'Alajuelo',
      'ALB',
      'Alberta',
      'Alger',
      'Alta Verapaz',
      'Amazonas',
      'Ancash',
      'Anhui',
      'Antioquia',
      'Antofagasta',
      'Apurimac',
      'AR',
      'Aragua',
      'Araucania',
      'Arequipa',
      'ARIZ',
      'Artigas',
      'Atacama',
      'Atlantida',
      'Ayacucho',
      'AZ',
      'AZ Territory',
      'Azuay',
      'B.C.S.',
      'Bac Phan',
      'Bahia',
      'Baja California',
      'Baja California Sur',
      'Baja Verapaz',
      'Baleares',
      'Baluchistan',
      'Banguey Island',
      'Barinas',
      'BCS',
      'Benguet',
      'Binh Tri Thien, Tinh',
      'Biobio, Regio del',
      'Bismarck Archipelago',
      'BN',
      'Bohol',
      'Bolivar',
      'Boyaca',
      'British Columbia',
      'Brunei',
      'Buenos Aires',
      'Bulacan',
      'CA',
      'Cajamarca',
      'Campeche',
      'Canar',
      'Cape Province',
      'Carchi',
      'Caroline Islands',
      'Cartago',
      'Cascajal',
      'Cataluna',
      'Cauca',
      'Cebu',
      'Central',
      'Chalatenango',
      'CHI',
      'Chia',
      'Chiang Mai, Changwat',
      'Chiapas',
      'Chihuahua',
      'Chimaltenango',
      'Chimborazo',
      'Chinandega',
      'Chiriqui',
      'Chontales',
      'Chupadero',
      'Chuquisaca',
      'CO',
      'CO Territory',
      'Coahuila',
      'COCA',
      'Cochabamba',
      'Cocle',
      'COL',
      'Colima',
      'Comayagua',
      'Concepcion',
      'COP',
      'Coquimbo',
      'Cordoba',
      'Cortes',
      'Costa',
      'Cotopaxi',
      'CT',
      'Cundinamarca',
      'Cuzco',
      'Darien',
      'DE',
      'Dept. La e',
      'Dept. Mag',
      'Distrito Federal',
      'DUR',
      'Durango',
      'East Malaysia',
      'East Sepik',
      'Eastern Division',
      'Eastern Divsion',
      'El Progreso',
      'Esmeraldas',
      'Esteli',
      'FL',
      'Florida',
      'Fujian',
      'GA',
      'Gansu',
      'Goias',
      'Golestan',
      'Granada',
      'GRO',
      'GUAM',
      'Guanacaste',
      'Guanajuato',
      'Guangdong',
      'Guatemala',
      'Guayas',
      'Guerrero',
      'Guizhou',
      'Ha Bach, Tinh',
      'Hainan',
      'Halland',
      'Hamadan',
      'Heidelberg',
      'Heredia',
      'HI',
      'Hidalgo',
      'Honshu',
      'Huancabamba',
      'Huancavelica',
      'Huanuco',
      'Hubei',
      'Huehuetena',
      'Huehuetenango',
      'Humacao',
      'IA',
      'ID',
      'Idaho',
      'IL',
      'IN',
      'Insular',
      'Ipiros',
      'Iqnique Province',
      'Iringa',
      'Isabela',
      'Izabel',
      'JAL',
      'Jalisco',
      'Jalsico',
      'Jawa Timur',
      'Jiangsu',
      'Jujuy',
      'Junin',
      'Kangean',
      'Khorasan Province',
      'Kkanh Hoa',
      'KS',
      'KwaZulu-Natal',
      'KY',
      'LA',
      'La Habana',
      'La Libertad',
      'La Paz',
      'La Vega',
      'Lambayeque',
      'Las Villas',
      'LASAN',
      'Leon',
      'Lima',
      'Limon',
      'Loja',
      'Loreto',
      'Luzon',
      'MA',
      'Madre de Dios',
      'Magdalena',
      'Maldonado',
      'Manabi',
      'Manitoba',
      'Mariana Islands',
      'Mato Grosso',
      'Matto Grosso',
      'Mayaguez',
      'Mazandaran',
      'MD',
      'ME',
      'Merida',
      'Meta',
      'Mexico',
      'MI',
      'MIC',
      'MICH',
      'Michoacan',
      'Minas Gerais',
      'Mindanao',
      'Misiones',
      'MN',
      'MO',
      'MON',
      'Montevideo',
      'Morazan',
      'Morelos',
      'MS',
      'MT',
      'MX',
      'N. Segovia',
      'Narino',
      'NAY',
      'Nayarit',
      'NC',
      'ND',
      'NE',
      'Neuvo Leon',
      'Nevada',
      'New Brunswick',
      'New South Wales',
      'Newfoundland',
      'NH',
      'NJ',
      'NL',
      'NM',
      'NM-TX',
      'Nord',
      'Norte',
      'Norte de Santander',
      'North Ayrshire',
      'Northeastern',
      'Northern',
      'Northern Division',
      'Northern Territory',
      'Northwest Frontier',
      'Northwest Territories',
      'Nova Scotia',
      'Nuevo Leon',
      'Nunavut',
      'NV',
      'NY',
      'O',
      'Oaxaca',
      'OH',
      'OK',
      'Ontario',
      'OR',
      'OR (?)',
      'OR or WA',
      'Oregon',
      'Oriente',
      'Otuzco',
      'PA',
      'Palawan',
      'Panama',
      'Panay',
      'Paraguari',
      'Parana',
      'Paris',
      'Pasco',
      'Pataz',
      'PE',
      'Peloponnisos',
      'Peten',
      'Pichincha',
      'Piura',
      'PMG',
      'Pohnpei',
      'Pomeroon-Supernaam',
      'Portuguesa',
      'Potosi',
      'PRE',
      'Prince Edward Island',
      'PUE',
      'Puebla',
      'Puerto Rico',
      'Puno',
      'Puntarenas',
      'Quang Ngai',
      'Quebec',
      'Queensland',
      'Quezaltenango',
      'Quezon',
      'Quiche',
      'RI',
      'Rio de Janeiro',
      'Rizal',
      'S Catarina',
      'S L Potosi',
      'S.L. Potos',
      'Sabah',
      'Salta',
      'Samar',
      'San Blas',
      'San Jose',
      'San Luis',
      'San Luis a',
      'San Luis Potosi',
      'San Martin',
      'San Miguel',
      'San Pedro',
      'Santa Barbara',
      'Santa Catarina',
      'Santa Cruz',
      'Santander',
      'Santiago, Region Met',
      'Sao Paulo',
      'Sarawak',
      'Saskatchewan',
      'Savaii Island',
      'SC',
      'Scotland',
      'SD',
      'Semnan',
      'Seybo',
      'Sichuan',
      'Sierra',
      'SIN',
      'Sinaloa',
      'SL Potosi',
      'Societe, Iles de la',
      'Societe, Isles de la',
      'SON',
      'Sonora',
      'Sonsonate',
      'South Australia',
      'Southern Cook Island',
      'St. Andrew',
      'St. Croix',
      'Stann Creek',
      'Sulu',
      'Sumatera',
      'TAB',
      'Tabasco',
      'Tachira',
      'Tacna',
      'TAM',
      'Tamaulipas',
      'Tarank Province',
      'Tarija',
      'Tarma',
      'Tasmania',
      'Tehran',
      'Tierra del Fuego',
      'Tlaxcala',
      'TN',
      'Toledo',
      'Tongatapu',
      'Trelawny',
      'Trujillo',
      'Tuamotu, Archipel de',
      'Tubuai, Iles',
      'Tucuman',
      'Tutuila Island',
      'TX',
      'TX ',
      'TX-NM',
      'Upolu Island',
      'UT',
      'Utah',
      'VA',
      'Valle',
      'Valparaiso',
      'Vaupes',
      'Veracruz',
      'Verguas',
      'Victoria',
      'VT',
      'w TX to NM',
      'w. TX - El Paso, NM',
      'w. TX - El Paso,NM',
      'WA',
      'WA Territory',
      'Wales',
      'WAS',
      'Western Australia',
      'Western Cape',
      'WI',
      'WN',
      'WV',
      'WY',
      'Wyoming',
      'Xizang',
      'Yaracuy',
      'Yoro',
      'Yucatan',
      'Yukon Territory',
      'Yunnan',
      'Zacatecas',
      'Zhejiang',
      'Zulia',
    ],
    messages: defineMessages({
      Unknown: {
        id: 'option.states.Unknown',
        defaultMessage: 'unknown',
      },
    }),
  },
  countries: {
    values: [
      'unknown',
      'Afghanistan',
      'AX',
      'AL',
      'Algeria',
      'American Samoa',
      'AD',
      'AO',
      'AI',
      'AQ',
      'Antigua',
      'Antigua and Barbuda',
      'Argentina',
      'Armenia',
      'AW',
      'Australia',
      'AT',
      'AZ',
      'BS',
      'BH',
      'BD',
      'BB',
      'BY',
      'Belgium',
      'Belize',
      'BJ',
      'Bermuda',
      'BT',
      'Bolivia',
      'BQ',
      'Borneo',
      'BA',
      'BW',
      'BV',
      'Brazil',
      'IO',
      'Brunei',
      'BG',
      'BF',
      'BI',
      'Cambodia',
      'Cameroon',
      'Canada',
      'CV',
      'KY',
      'CF',
      'TD',
      'Chile',
      'China',
      'CX',
      'CC',
      'Colombia',
      'KM',
      'CG',
      'Cook Islands',
      'Costa Rica',
      'CI',
      'Croatia',
      'Cuba',
      'CW',
      'CY',
      'CZ',
      'D R Congo',
      'Denmark',
      'DJ',
      'DM',
      'Dominican Republic',
      'Ecuador',
      'EG',
      'El Salvador',
      'Ellas',
      'Equatorial Guinea',
      'ER',
      'Espana',
      'EE',
      'ET',
      'FK',
      'FO',
      'Fiji',
      'Finland',
      'France',
      'GF',
      'PF',
      'TF',
      'GA',
      'GM',
      'GE',
      'Germany',
      'GH',
      'GI',
      'Greenland',
      'GD',
      'Guadeloupe',
      'GU',
      'Guatemala',
      'GG',
      'GN',
      'GW',
      'Guyana',
      'Haiti',
      'HM',
      'Hispaniola',
      'VA',
      'Honduras',
      'HK',
      'HN',
      'Iceland',
      'India',
      'Indonesia',
      'Iran',
      'IQ',
      'Ireland',
      'IM',
      'Israel',
      'Italy',
      'Jamaica',
      'Japan',
      'JE',
      'Jordan',
      'KZ',
      'Kenya',
      'KI',
      'KP',
      'KW',
      'KG',
      'LA',
      'LV',
      'Lebanon',
      'LS',
      'LR',
      'LY',
      'LI',
      'LT',
      'LU',
      'MO',
      'MK',
      'Madagascar',
      'Malawi',
      'Malaysia',
      'MV',
      'ML',
      'MT',
      'Marshall Islands',
      'MQ',
      'MR',
      'MU',
      'YT',
      'Mexico',
      'Micronesia',
      'MD',
      'MC',
      'Mongolia',
      'ME',
      'MS',
      'Morocco',
      'MZ',
      'Myanmar',
      'Namibia',
      'NR',
      'Nepal',
      'Netherlands Antilles',
      'Netherlands',
      'New Caledonia',
      'New Zealand',
      'Nicaragua',
      'NE',
      'NG',
      'Nihon',
      'Niue',
      'NF',
      'MP',
      'Norway',
      'OM',
      'Pakistan',
      'PW',
      'PS',
      'Panama',
      'Papua New Guinea',
      'Paraguay',
      'Peru',
      'Philippines',
      'PN',
      'PL',
      'Polynesia',
      'Polynesie francaise',
      'Portugal',
      'Prathet Thai',
      'Puerto Rico',
      'QA',
      'Republica Dominicana',
      'Reunion',
      'RO',
      'Russia',
      'RW',
      'BL',
      'Saint Helena',
      'KN',
      'Saint Lucia',
      'MF',
      'PM',
      'VC',
      'Samoa',
      'SM',
      'ST',
      'SA',
      'Scotland',
      'SN',
      'RS',
      'Seychelles',
      'SL',
      'SG',
      'SX',
      'SK',
      'Slovenia',
      'SO',
      'Solomon Islands',
      'South Africa',
      'GS',
      'South Korea',
      'SS',
      'Spain',
      'Sri Lanka',
      'Sudan',
      'Suriname',
      'SJ',
      'SZ',
      'Sweden',
      'CH',
      'Syria',
      'Taiwan',
      'TJ',
      'Tanzania',
      'Thailand',
      'TL',
      'TG',
      'TK',
      'Tonga',
      'Trinidad and Tobago',
      'TN',
      'Turkey',
      'TM',
      'TC',
      'TV',
      'Uganda',
      'UA',
      'AE',
      'United Kingdom',
      'UM',
      'Uruguay',
      'USA',
      'UZ',
      'Vanuatu',
      'Venezuela',
      'Viet Nam',
      'VG',
      'Virgin Islands',
      'WF',
      'EH',
      'Western Samoa',
      'YE',
      'ZM',
      'Zhonghua',
      'ZW',
    ],
    messages: defineMessages({
      unknown: {
        id: 'option.countries.unknown',
        defaultMessage: 'unknown',
      },
      Afghanistan: {
        id: 'option.countries.Afghanistan',
        defaultMessage: 'Afghanistan',
      },
      AX: {
        id: 'option.countries.AX',
        defaultMessage: 'Åland Islands',
      },
      AL: {
        id: 'option.countries.AL',
        defaultMessage: 'Albania',
      },
      Algeria: {
        id: 'option.countries.Algeria',
        defaultMessage: 'Algeria',
      },
      'American Samoa': {
        id: 'option.countries.American Samoa',
        defaultMessage: 'American Samoa',
      },
      AD: {
        id: 'option.countries.AD',
        defaultMessage: 'Andorra',
      },
      AO: {
        id: 'option.countries.AO',
        defaultMessage: 'Angola',
      },
      AI: {
        id: 'option.countries.AI',
        defaultMessage: 'Anguilla',
      },
      AQ: {
        id: 'option.countries.AQ',
        defaultMessage: 'Antarctica',
      },
      Antigua: {
        id: 'option.countries.Antigua',
        defaultMessage: 'Antigua',
      },
      'Antigua and Barbuda': {
        id: 'option.countries.Antigua and Barbuda',
        defaultMessage: 'Antigua and Barbuda',
      },
      Argentina: {
        id: 'option.countries.Argentina',
        defaultMessage: 'Argentina',
      },
      Armenia: {
        id: 'option.countries.Armenia',
        defaultMessage: 'Armenia',
      },
      AW: {
        id: 'option.countries.AW',
        defaultMessage: 'Aruba',
      },
      Australia: {
        id: 'option.countries.Australia',
        defaultMessage: 'Australia',
      },
      AT: {
        id: 'option.countries.AT',
        defaultMessage: 'Austria',
      },
      AZ: {
        id: 'option.countries.AZ',
        defaultMessage: 'Azerbaijan',
      },
      BS: {
        id: 'option.countries.BS',
        defaultMessage: 'Bahamas',
      },
      BH: {
        id: 'option.countries.BH',
        defaultMessage: 'Bahrain',
      },
      BD: {
        id: 'option.countries.BD',
        defaultMessage: 'Bangladesh',
      },
      BB: {
        id: 'option.countries.BB',
        defaultMessage: 'Barbados',
      },
      BY: {
        id: 'option.countries.BY',
        defaultMessage: 'Belarus',
      },
      Belgium: {
        id: 'option.countries.Belgium',
        defaultMessage: 'Belgium',
      },
      Belize: {
        id: 'option.countries.Belize',
        defaultMessage: 'Belize',
      },
      BJ: {
        id: 'option.countries.BJ',
        defaultMessage: 'Benin',
      },
      Bermuda: {
        id: 'option.countries.Bermuda',
        defaultMessage: 'Bermuda',
      },
      BT: {
        id: 'option.countries.BT',
        defaultMessage: 'Bhutan',
      },
      Bolivia: {
        id: 'option.countries.Bolivia',
        defaultMessage: 'Bolivia',
      },
      BQ: {
        id: 'option.countries.BQ',
        defaultMessage: 'Bonaire, Sint Eustatius and Saba',
      },
      Borneo: {
        id: 'option.countries.Borneo',
        defaultMessage: 'Borneo',
      },
      BA: {
        id: 'option.countries.BA',
        defaultMessage: 'Bosnia and Herzegovina',
      },
      BW: {
        id: 'option.countries.BW',
        defaultMessage: 'Botswana',
      },
      BV: {
        id: 'option.countries.BV',
        defaultMessage: 'Bouvet Island',
      },
      Brazil: {
        id: 'option.countries.Brazil',
        defaultMessage: 'Brazil',
      },
      IO: {
        id: 'option.countries.IO',
        defaultMessage: 'British Indian Ocean Territory',
      },
      Brunei: {
        id: 'option.countries.Brunei',
        defaultMessage: 'Brunei',
      },
      BG: {
        id: 'option.countries.BG',
        defaultMessage: 'Bulgaria',
      },
      BF: {
        id: 'option.countries.BF',
        defaultMessage: 'Burkina Faso',
      },
      BI: {
        id: 'option.countries.BI',
        defaultMessage: 'Burundi',
      },
      Cambodia: {
        id: 'option.countries.Cambodia',
        defaultMessage: 'Cambodia',
      },
      Cameroon: {
        id: 'option.countries.Cameroon',
        defaultMessage: 'Cameroon',
      },
      Canada: {
        id: 'option.countries.Canada',
        defaultMessage: 'Canada',
      },
      CV: {
        id: 'option.countries.CV',
        defaultMessage: 'Cape Verde',
      },
      KY: {
        id: 'option.countries.KY',
        defaultMessage: 'Cayman Islands',
      },
      CF: {
        id: 'option.countries.CF',
        defaultMessage: 'Central African Republic',
      },
      TD: {
        id: 'option.countries.TD',
        defaultMessage: 'Chad',
      },
      Chile: {
        id: 'option.countries.Chile',
        defaultMessage: 'Chile',
      },
      China: {
        id: 'option.countries.China',
        defaultMessage: 'China',
      },
      CX: {
        id: 'option.countries.CX',
        defaultMessage: 'Christmas Island',
      },
      CC: {
        id: 'option.countries.CC',
        defaultMessage: 'Cocos (Keeling) Islands',
      },
      Colombia: {
        id: 'option.countries.Colombia',
        defaultMessage: 'Colombia',
      },
      KM: {
        id: 'option.countries.KM',
        defaultMessage: 'Comoros',
      },
      CG: {
        id: 'option.countries.CG',
        defaultMessage: 'Congo',
      },
      'Cook Islands': {
        id: 'option.countries.Cook Islands',
        defaultMessage: 'Cook Islands',
      },
      'Costa Rica': {
        id: 'option.countries.Costa Rica',
        defaultMessage: 'Costa Rica',
      },
      CI: {
        id: 'option.countries.CI',
        defaultMessage: 'Côte d’Ivoire',
      },
      Croatia: {
        id: 'option.countries.Croatia',
        defaultMessage: 'Croatia',
      },
      Cuba: {
        id: 'option.countries.Cuba',
        defaultMessage: 'Cuba',
      },
      CW: {
        id: 'option.countries.CW',
        defaultMessage: 'Curaçao',
      },
      CY: {
        id: 'option.countries.CY',
        defaultMessage: 'Cyprus',
      },
      CZ: {
        id: 'option.countries.CZ',
        defaultMessage: 'Czech Republic',
      },
      'D R Congo': {
        id: 'option.countries.D R Congo',
        defaultMessage: 'D R Congo',
      },
      Denmark: {
        id: 'option.countries.Denmark',
        defaultMessage: 'Denmark',
      },
      DJ: {
        id: 'option.countries.DJ',
        defaultMessage: 'Djibouti',
      },
      DM: {
        id: 'option.countries.DM',
        defaultMessage: 'Dominica',
      },
      'Dominican Republic': {
        id: 'option.countries.Dominican Republic',
        defaultMessage: 'Dominican Republic',
      },
      Ecuador: {
        id: 'option.countries.Ecuador',
        defaultMessage: 'Ecuador',
      },
      EG: {
        id: 'option.countries.EG',
        defaultMessage: 'Egypt',
      },
      'El Salvador': {
        id: 'option.countries.El Salvador',
        defaultMessage: 'El Salvador',
      },
      Ellas: {
        id: 'option.countries.Ellas',
        defaultMessage: 'Ellas',
      },
      'Equatorial Guinea': {
        id: 'option.countries.Equatorial Guinea',
        defaultMessage: 'Equatorial Guinea',
      },
      ER: {
        id: 'option.countries.ER',
        defaultMessage: 'Eritrea',
      },
      Espana: {
        id: 'option.countries.Espana',
        defaultMessage: 'Espana',
      },
      EE: {
        id: 'option.countries.EE',
        defaultMessage: 'Estonia',
      },
      ET: {
        id: 'option.countries.ET',
        defaultMessage: 'Ethiopia',
      },
      FK: {
        id: 'option.countries.FK',
        defaultMessage: 'Falkland Islands (Malvinas)',
      },
      FO: {
        id: 'option.countries.FO',
        defaultMessage: 'Faroe Islands',
      },
      Fiji: {
        id: 'option.countries.Fiji',
        defaultMessage: 'Fiji',
      },
      Finland: {
        id: 'option.countries.Finland',
        defaultMessage: 'Finland',
      },
      France: {
        id: 'option.countries.France',
        defaultMessage: 'France',
      },
      GF: {
        id: 'option.countries.GF',
        defaultMessage: 'French Guiana',
      },
      PF: {
        id: 'option.countries.PF',
        defaultMessage: 'French Polynesia',
      },
      TF: {
        id: 'option.countries.TF',
        defaultMessage: 'French Southern Territories',
      },
      GA: {
        id: 'option.countries.GA',
        defaultMessage: 'Gabon',
      },
      GM: {
        id: 'option.countries.GM',
        defaultMessage: 'Gambia',
      },
      GE: {
        id: 'option.countries.GE',
        defaultMessage: 'Georgia',
      },
      Germany: {
        id: 'option.countries.Germany',
        defaultMessage: 'Germany',
      },
      GH: {
        id: 'option.countries.GH',
        defaultMessage: 'Ghana',
      },
      GI: {
        id: 'option.countries.GI',
        defaultMessage: 'Gibraltar',
      },
      Greenland: {
        id: 'option.countries.Greenland',
        defaultMessage: 'Greenland',
      },
      GD: {
        id: 'option.countries.GD',
        defaultMessage: 'Grenada',
      },
      Guadeloupe: {
        id: 'option.countries.Guadeloupe',
        defaultMessage: 'Guadeloupe',
      },
      GU: {
        id: 'option.countries.GU',
        defaultMessage: 'Guam',
      },
      Guatemala: {
        id: 'option.countries.Guatemala',
        defaultMessage: 'Guatemala',
      },
      GG: {
        id: 'option.countries.GG',
        defaultMessage: 'Guernsey',
      },
      GN: {
        id: 'option.countries.GN',
        defaultMessage: 'Guinea',
      },
      GW: {
        id: 'option.countries.GW',
        defaultMessage: 'Guinea-Bissau',
      },
      Guyana: {
        id: 'option.countries.Guyana',
        defaultMessage: 'Guyana',
      },
      Haiti: {
        id: 'option.countries.Haiti',
        defaultMessage: 'Haiti',
      },
      HM: {
        id: 'option.countries.HM',
        defaultMessage: 'Heard Island and McDonald Islands',
      },
      Hispaniola: {
        id: 'option.countries.Hispaniola',
        defaultMessage: 'Hispaniola',
      },
      VA: {
        id: 'option.countries.VA',
        defaultMessage: 'Holy See (Vatican City State)',
      },
      Honduras: {
        id: 'option.countries.Honduras',
        defaultMessage: 'Honduras',
      },
      HK: {
        id: 'option.countries.HK',
        defaultMessage: 'Hong Kong',
      },
      HN: {
        id: 'option.countries.HN',
        defaultMessage: 'Hungary',
      },
      Iceland: {
        id: 'option.countries.Iceland',
        defaultMessage: 'Iceland',
      },
      India: {
        id: 'option.countries.India',
        defaultMessage: 'India',
      },
      Indonesia: {
        id: 'option.countries.Indonesia',
        defaultMessage: 'Indonesia',
      },
      Iran: {
        id: 'option.countries.Iran',
        defaultMessage: 'Iran',
      },
      IQ: {
        id: 'option.countries.IQ',
        defaultMessage: 'Iraq',
      },
      Ireland: {
        id: 'option.countries.Ireland',
        defaultMessage: 'Ireland',
      },
      IM: {
        id: 'option.countries.IM',
        defaultMessage: 'Isle of Man',
      },
      Israel: {
        id: 'option.countries.Israel',
        defaultMessage: 'Israel',
      },
      Italy: {
        id: 'option.countries.Italy',
        defaultMessage: 'Italy',
      },
      Jamaica: {
        id: 'option.countries.Jamaica',
        defaultMessage: 'Jamaica',
      },
      Japan: {
        id: 'option.countries.Japan',
        defaultMessage: 'Japan',
      },
      JE: {
        id: 'option.countries.JE',
        defaultMessage: 'Jersey',
      },
      Jordan: {
        id: 'option.countries.Jordan',
        defaultMessage: 'Jordan',
      },
      KZ: {
        id: 'option.countries.KZ',
        defaultMessage: 'Kazakhstan',
      },
      Kenya: {
        id: 'option.countries.Kenya',
        defaultMessage: 'Kenya',
      },
      KI: {
        id: 'option.countries.KI',
        defaultMessage: 'Kiribati',
      },
      KP: {
        id: 'option.countries.KP',
        defaultMessage: 'Korea, Democratic People’s Republic of',
      },
      KW: {
        id: 'option.countries.KW',
        defaultMessage: 'Kuwait',
      },
      KG: {
        id: 'option.countries.KG',
        defaultMessage: 'Kyrgyzstan',
      },
      LA: {
        id: 'option.countries.LA',
        defaultMessage: 'Lao People’s Democratic Republic',
      },
      LV: {
        id: 'option.countries.LV',
        defaultMessage: 'Latvia',
      },
      Lebanon: {
        id: 'option.countries.Lebanon',
        defaultMessage: 'Lebanon',
      },
      LS: {
        id: 'option.countries.LS',
        defaultMessage: 'Lesotho',
      },
      LR: {
        id: 'option.countries.LR',
        defaultMessage: 'Liberia',
      },
      LY: {
        id: 'option.countries.LY',
        defaultMessage: 'Libya',
      },
      LI: {
        id: 'option.countries.LI',
        defaultMessage: 'Liechtenstein',
      },
      LT: {
        id: 'option.countries.LT',
        defaultMessage: 'Lithuania',
      },
      LU: {
        id: 'option.countries.LU',
        defaultMessage: 'Luxembourg',
      },
      MO: {
        id: 'option.countries.MO',
        defaultMessage: 'Macao',
      },
      MK: {
        id: 'option.countries.MK',
        defaultMessage: 'Macedonia, the Former Yugoslav Republic of',
      },
      Madagascar: {
        id: 'option.countries.Madagascar',
        defaultMessage: 'Madagascar',
      },
      Malawi: {
        id: 'option.countries.Malawi',
        defaultMessage: 'Malawi',
      },
      Malaysia: {
        id: 'option.countries.Malaysia',
        defaultMessage: 'Malaysia',
      },
      MV: {
        id: 'option.countries.MV',
        defaultMessage: 'Maldives',
      },
      ML: {
        id: 'option.countries.ML',
        defaultMessage: 'Mali',
      },
      MT: {
        id: 'option.countries.MT',
        defaultMessage: 'Malta',
      },
      'Marshall Islands': {
        id: 'option.countries.Marshall Islands',
        defaultMessage: 'Marshall Islands',
      },
      MQ: {
        id: 'option.countries.MQ',
        defaultMessage: 'Martinique',
      },
      MR: {
        id: 'option.countries.MR',
        defaultMessage: 'Mauritania',
      },
      MU: {
        id: 'option.countries.MU',
        defaultMessage: 'Mauritius',
      },
      YT: {
        id: 'option.countries.YT',
        defaultMessage: 'Mayotte',
      },
      Mexico: {
        id: 'option.countries.Mexico',
        defaultMessage: 'Mexico',
      },
      Micronesia: {
        id: 'option.countries.Micronesia',
        defaultMessage: 'Micronesia',
      },
      MD: {
        id: 'option.countries.MD',
        defaultMessage: 'Moldova, Republic of',
      },
      MC: {
        id: 'option.countries.MC',
        defaultMessage: 'Monaco',
      },
      Mongolia: {
        id: 'option.countries.Mongolia',
        defaultMessage: 'Mongolia',
      },
      ME: {
        id: 'option.countries.ME',
        defaultMessage: 'Montenegro',
      },
      MS: {
        id: 'option.countries.MS',
        defaultMessage: 'Montserrat',
      },
      Morocco: {
        id: 'option.countries.Morocco',
        defaultMessage: 'Morocco',
      },
      MZ: {
        id: 'option.countries.MZ',
        defaultMessage: 'Mozambique',
      },
      Myanmar: {
        id: 'option.countries.Myanmar',
        defaultMessage: 'Myanmar',
      },
      Namibia: {
        id: 'option.countries.Namibia',
        defaultMessage: 'Namibia',
      },
      NR: {
        id: 'option.countries.NR',
        defaultMessage: 'Nauru',
      },
      Nepal: {
        id: 'option.countries.Nepal',
        defaultMessage: 'Nepal',
      },
      'Netherlands Antilles': {
        id: 'option.countries.Netherlands Antilles',
        defaultMessage: 'Netherlands Antilles',
      },
      Netherlands: {
        id: 'option.countries.Netherlands',
        defaultMessage: 'Netherlands',
      },
      'New Caledonia': {
        id: 'option.countries.New Caledonia',
        defaultMessage: 'New Caledonia',
      },
      'New Zealand': {
        id: 'option.countries.New Zealand',
        defaultMessage: 'New Zealand',
      },
      Nicaragua: {
        id: 'option.countries.Nicaragua',
        defaultMessage: 'Nicaragua',
      },
      NE: {
        id: 'option.countries.NE',
        defaultMessage: 'Niger',
      },
      NG: {
        id: 'option.countries.NG',
        defaultMessage: 'Nigeria',
      },
      Nihon: {
        id: 'option.countries.Nihon',
        defaultMessage: 'Nihon',
      },
      Niue: {
        id: 'option.countries.Niue',
        defaultMessage: 'Niue',
      },
      NF: {
        id: 'option.countries.NF',
        defaultMessage: 'Norfolk Island',
      },
      MP: {
        id: 'option.countries.MP',
        defaultMessage: 'Northern Mariana Islands',
      },
      Norway: {
        id: 'option.countries.Norway',
        defaultMessage: 'Norway',
      },
      OM: {
        id: 'option.countries.OM',
        defaultMessage: 'Oman',
      },
      Pakistan: {
        id: 'option.countries.Pakistan',
        defaultMessage: 'Pakistan',
      },
      PW: {
        id: 'option.countries.PW',
        defaultMessage: 'Palau',
      },
      PS: {
        id: 'option.countries.PS',
        defaultMessage: 'Palestinian Territory, Occupied',
      },
      Panama: {
        id: 'option.countries.Panama',
        defaultMessage: 'Panama',
      },
      'Papua New Guinea': {
        id: 'option.countries.Papua New Guinea',
        defaultMessage: 'Papua New Guinea',
      },
      Paraguay: {
        id: 'option.countries.Paraguay',
        defaultMessage: 'Paraguay',
      },
      Peru: {
        id: 'option.countries.Peru',
        defaultMessage: 'Peru',
      },
      Philippines: {
        id: 'option.countries.Philippines',
        defaultMessage: 'Philippines',
      },
      PN: {
        id: 'option.countries.PN',
        defaultMessage: 'Pitcairn',
      },
      PL: {
        id: 'option.countries.PL',
        defaultMessage: 'Poland',
      },
      Polynesia: {
        id: 'option.countries.Polynesia',
        defaultMessage: 'Polynesia',
      },
      'Polynesie francaise': {
        id: 'option.countries.Polynesie francaise',
        defaultMessage: 'Polynesie francaise',
      },
      Portugal: {
        id: 'option.countries.Portugal',
        defaultMessage: 'Portugal',
      },
      'Prathet Thai': {
        id: 'option.countries.Prathet Thai',
        defaultMessage: 'Prathet Thai',
      },
      'Puerto Rico': {
        id: 'option.countries.Puerto Rico',
        defaultMessage: 'Puerto Rico',
      },
      QA: {
        id: 'option.countries.QA',
        defaultMessage: 'Qatar',
      },
      'Republica Dominicana': {
        id: 'option.countries.Republica Dominicana',
        defaultMessage: 'Republica Dominicana',
      },
      Reunion: {
        id: 'option.countries.Reunion',
        defaultMessage: 'Reunion',
      },
      RO: {
        id: 'option.countries.RO',
        defaultMessage: 'Romania',
      },
      Russia: {
        id: 'option.countries.Russia',
        defaultMessage: 'Russia',
      },
      RW: {
        id: 'option.countries.RW',
        defaultMessage: 'Rwanda',
      },
      BL: {
        id: 'option.countries.BL',
        defaultMessage: 'Saint Barthélemy',
      },
      'Saint Helena': {
        id: 'option.countries.Saint Helena',
        defaultMessage: 'Saint Helena',
      },
      KN: {
        id: 'option.countries.KN',
        defaultMessage: 'Saint Kitts and Nevis',
      },
      'Saint Lucia': {
        id: 'option.countries.Saint Lucia',
        defaultMessage: 'Saint Lucia',
      },
      MF: {
        id: 'option.countries.MF',
        defaultMessage: 'Saint Martin (French Part)',
      },
      PM: {
        id: 'option.countries.PM',
        defaultMessage: 'Saint Pierre and Miquelon',
      },
      VC: {
        id: 'option.countries.VC',
        defaultMessage: 'Saint Vincent and the Grenadines',
      },
      Samoa: {
        id: 'option.countries.Samoa',
        defaultMessage: 'Samoa',
      },
      SM: {
        id: 'option.countries.SM',
        defaultMessage: 'San Marino',
      },
      ST: {
        id: 'option.countries.ST',
        defaultMessage: 'Sao Tome and Principe',
      },
      SA: {
        id: 'option.countries.SA',
        defaultMessage: 'Saudi Arabia',
      },
      Scotland: {
        id: 'option.countries.Scotland',
        defaultMessage: 'Scotland',
      },
      SN: {
        id: 'option.countries.SN',
        defaultMessage: 'Senegal',
      },
      RS: {
        id: 'option.countries.RS',
        defaultMessage: 'Serbia',
      },
      Seychelles: {
        id: 'option.countries.Seychelles',
        defaultMessage: 'Seychelles',
      },
      SL: {
        id: 'option.countries.SL',
        defaultMessage: 'Sierra Leone',
      },
      SG: {
        id: 'option.countries.SG',
        defaultMessage: 'Singapore',
      },
      SX: {
        id: 'option.countries.SX',
        defaultMessage: 'Sint Maarten (Dutch Part)',
      },
      SK: {
        id: 'option.countries.SK',
        defaultMessage: 'Slovakia',
      },
      Slovenia: {
        id: 'option.countries.Slovenia',
        defaultMessage: 'Slovenia',
      },
      SO: {
        id: 'option.countries.SO',
        defaultMessage: 'Somalia',
      },
      'Solomon Islands': {
        id: 'option.countries.Solomon Islands',
        defaultMessage: 'Solomon Islands',
      },
      'South Africa': {
        id: 'option.countries.South Africa',
        defaultMessage: 'South Africa',
      },
      GS: {
        id: 'option.countries.GS',
        defaultMessage: 'South Georgia and the South Sandwich Islands',
      },
      'South Korea': {
        id: 'option.countries.South Korea',
        defaultMessage: 'South Korea',
      },
      SS: {
        id: 'option.countries.SS',
        defaultMessage: 'South Sudan',
      },
      Spain: {
        id: 'option.countries.Spain',
        defaultMessage: 'Spain',
      },
      'Sri Lanka': {
        id: 'option.countries.Sri Lanka',
        defaultMessage: 'Sri Lanka',
      },
      Sudan: {
        id: 'option.countries.Sudan',
        defaultMessage: 'Sudan',
      },
      Suriname: {
        id: 'option.countries.Suriname',
        defaultMessage: 'Suriname',
      },
      SJ: {
        id: 'option.countries.SJ',
        defaultMessage: 'Svalbard and Jan Mayen',
      },
      SZ: {
        id: 'option.countries.SZ',
        defaultMessage: 'Swaziland',
      },
      Sweden: {
        id: 'option.countries.Sweden',
        defaultMessage: 'Sweden',
      },
      CH: {
        id: 'option.countries.CH',
        defaultMessage: 'Switzerland',
      },
      Syria: {
        id: 'option.countries.Syria',
        defaultMessage: 'Syria',
      },
      Taiwan: {
        id: 'option.countries.Taiwan',
        defaultMessage: 'Taiwan',
      },
      TJ: {
        id: 'option.countries.TJ',
        defaultMessage: 'Tajikistan',
      },
      Tanzania: {
        id: 'option.countries.Tanzania',
        defaultMessage: 'Tanzania',
      },
      Thailand: {
        id: 'option.countries.Thailand',
        defaultMessage: 'Thailand',
      },
      TL: {
        id: 'option.countries.TL',
        defaultMessage: 'Timor-Leste',
      },
      TG: {
        id: 'option.countries.TG',
        defaultMessage: 'Togo',
      },
      TK: {
        id: 'option.countries.TK',
        defaultMessage: 'Tokelau',
      },
      Tonga: {
        id: 'option.countries.Tonga',
        defaultMessage: 'Tonga',
      },
      'Trinidad and Tobago': {
        id: 'option.countries.Trinidad and Tobago',
        defaultMessage: 'Trinidad and Tobago',
      },
      TN: {
        id: 'option.countries.TN',
        defaultMessage: 'Tunisia',
      },
      Turkey: {
        id: 'option.countries.Turkey',
        defaultMessage: 'Turkey',
      },
      TM: {
        id: 'option.countries.TM',
        defaultMessage: 'Turkmenistan',
      },
      TC: {
        id: 'option.countries.TC',
        defaultMessage: 'Turks and Caicos Islands',
      },
      TV: {
        id: 'option.countries.TV',
        defaultMessage: 'Tuvalu',
      },
      Uganda: {
        id: 'option.countries.Uganda',
        defaultMessage: 'Uganda',
      },
      UA: {
        id: 'option.countries.UA',
        defaultMessage: 'Ukraine',
      },
      AE: {
        id: 'option.countries.AE',
        defaultMessage: 'United Arab Emirates',
      },
      'United Kingdom': {
        id: 'option.countries.United Kingdom',
        defaultMessage: 'United Kingdom',
      },
      UM: {
        id: 'option.countries.UM',
        defaultMessage: 'United States Minor Outlying Islands',
      },
      Uruguay: {
        id: 'option.countries.Uruguay',
        defaultMessage: 'Uruguay',
      },
      USA: {
        id: 'option.countries.USA',
        defaultMessage: 'USA',
      },
      UZ: {
        id: 'option.countries.UZ',
        defaultMessage: 'Uzbekistan',
      },
      Vanuatu: {
        id: 'option.countries.Vanuatu',
        defaultMessage: 'Vanuatu',
      },
      Venezuela: {
        id: 'option.countries.Venezuela',
        defaultMessage: 'Venezuela',
      },
      'Viet Nam': {
        id: 'option.countries.Viet Nam',
        defaultMessage: 'Viet Nam',
      },
      VG: {
        id: 'option.countries.VG',
        defaultMessage: 'Virgin Islands, British',
      },
      'Virgin Islands': {
        id: 'option.countries.Virgin Islands',
        defaultMessage: 'Virgin Islands',
      },
      WF: {
        id: 'option.countries.WF',
        defaultMessage: 'Wallis and Futuna',
      },
      EH: {
        id: 'option.countries.EH',
        defaultMessage: 'Western Sahara',
      },
      'Western Samoa': {
        id: 'option.countries.Western Samoa',
        defaultMessage: 'Western Samoa',
      },
      YE: {
        id: 'option.countries.YE',
        defaultMessage: 'Yemen',
      },
      ZM: {
        id: 'option.countries.ZM',
        defaultMessage: 'Zambia',
      },
      Zhonghua: {
        id: 'option.countries.Zhonghua',
        defaultMessage: 'Zhonghua',
      },
      ZW: {
        id: 'option.countries.ZW',
        defaultMessage: 'Zimbabwe',
      },
    }),
  },
  higherGeographies: {
    values: [
      'pacificocean',
      'North America',
    ],
    messages: defineMessages({
      pacificocean: {
        id: 'option.geographies.pacificocean',
        defaultMessage: 'Pacific Ocean',
      },
      'North America': {
        id: 'option.geographies.North America',
        defaultMessage: 'North America',
      },
    }),
  },
  geodeticDatums: {
    values: [
      'Not Recorded',
      'ADG66',
      'NAD27',
      'NAD83',
      'NAD83&amp;WGS84',
      'WGS84',
    ],
    messages: defineMessages({
      'Not Recorded': {
        id: 'option.geodeticDatums.Not Recorded',
        defaultMessage: 'not recorded',
      },
      'NAD83&amp;WGS84': {
        id: 'option.geodeticDatums.NAD83&amp;WGS84',
        defaultMessage: 'NAD83 & WGS84',
      },
    }),
  },
  coordUncertaintyUnits: {
    values: [
      'unknown',
      'feet',
      'kilometers',
      'meters',
      'miles',
    ],
    messages: defineMessages({
      unknown: {
        id: 'option.coordUncertaintyUnits.unknown',
        defaultMessage: 'unknown',
      },
      feet: {
        id: 'option.coordUncertaintyUnits.feet',
        defaultMessage: 'feet',
      },
      kilometers: {
        id: 'option.coordUncertaintyUnits.kilometers',
        defaultMessage: 'kilometers',
      },
      meters: {
        id: 'option.coordUncertaintyUnits.meters',
        defaultMessage: 'meters',
      },
      miles: {
        id: 'option.coordUncertaintyUnits.miles',
        defaultMessage: 'miles',
      },
    }),
  },
  depthUnits: {
    values: [
      'uncertain',
      'centimeters',
      'inches',
      'fathoms',
      'feet',
      'furlongs',
      'kilometers',
      'meters',
      'miles',
      'rods',
    ],
    messages: defineMessages({
      uncertain: {
        id: 'option.depthUnits.uncertain',
        defaultMessage: 'uncertain',
      },
      centimeters: {
        id: 'option.depthUnits.centimeters',
        defaultMessage: 'centimeters',
      },
      inches: {
        id: 'option.depthUnits.inches',
        defaultMessage: 'inches',
      },
      fathoms: {
        id: 'option.depthUnits.fathoms',
        defaultMessage: 'fathoms',
      },
      feet: {
        id: 'option.depthUnits.feet',
        defaultMessage: 'feet',
      },
      furlongs: {
        id: 'option.depthUnits.furlongs',
        defaultMessage: 'furlongs',
      },
      kilometers: {
        id: 'option.depthUnits.kilometers',
        defaultMessage: 'kilometers',
      },
      meters: {
        id: 'option.depthUnits.meters',
        defaultMessage: 'meters',
      },
      miles: {
        id: 'option.depthUnits.miles',
        defaultMessage: 'miles',
      },
      rods: {
        id: 'option.depthUnits.rods',
        defaultMessage: 'rods',
      },
    }),
  },
  elevationUnits: {
    values: [
      'uncertain',
      'feet',
      'meters',
    ],
    messages: defineMessages({
      uncertain: {
        id: 'option.elevationUnits.uncertain',
        defaultMessage: 'uncertain',
      },
      feet: {
        id: 'option.elevationUnits.feet',
        defaultMessage: 'feet',
      },
      meters: {
        id: 'option.elevationUnits.meters',
        defaultMessage: 'meters',
      },
    }),
  },
  distanceAboveSurfaceUnits: {
    values: [
      'uncertain',
      'centimeters',
      'inches',
      'fathoms',
      'feet',
      'furlongs',
      'kilometers',
      'meters',
      'miles',
      'rods',
    ],
    messages: defineMessages({
      uncertain: {
        id: 'option.distanceAboveSurfaceUnits.uncertain',
        defaultMessage: 'uncertain',
      },
      centimeters: {
        id: 'option.distanceAboveSurfaceUnits.centimeters',
        defaultMessage: 'centimeters',
      },
      inches: {
        id: 'option.distanceAboveSurfaceUnits.inches',
        defaultMessage: 'inches',
      },
      fathoms: {
        id: 'option.distanceAboveSurfaceUnits.fathoms',
        defaultMessage: 'fathoms',
      },
      feet: {
        id: 'option.distanceAboveSurfaceUnits.feet',
        defaultMessage: 'feet',
      },
      furlongs: {
        id: 'option.distanceAboveSurfaceUnits.furlongs',
        defaultMessage: 'furlongs',
      },
      kilometers: {
        id: 'option.distanceAboveSurfaceUnits.kilometers',
        defaultMessage: 'kilometers',
      },
      meters: {
        id: 'option.distanceAboveSurfaceUnits.meters',
        defaultMessage: 'meters',
      },
      miles: {
        id: 'option.distanceAboveSurfaceUnits.miles',
        defaultMessage: 'miles',
      },
      rods: {
        id: 'option.distanceAboveSurfaceUnits.rods',
        defaultMessage: 'rods',
      },
    }),
  },
  georefProtocols: {
    values: [
      'chapman-wieczorek-2006-guide-best-practices-georeferencing',
      'manis-herpnet-ornis-georeferencing-guidelines',
      'georeferencing-dummies',
      'biogeomancer',
    ],
    messages: defineMessages({
      'chapman-wieczorek-2006-guide-best-practices-georeferencing': {
        id: 'option.georefProtocols.chapman-wieczorek-2006-guide-best-practices-georeferencing',
        defaultMessage: 'Chapman, Wieczorek 2006, Guide to Best Practices for Georeferencing',
      },
      'manis-herpnet-ornis-georeferencing-guidelines': {
        id: 'option.georefProtocols.manis-herpnet-ornis-georeferencing-guidelines',
        defaultMessage: 'MaNIS/HerpNet/ORNIS Georeferencing Guidelines',
      },
      'georeferencing-dummies': {
        id: 'option.georefProtocols.georeferencing-dummies',
        defaultMessage: 'Georeferencing For Dummies',
      },
      biogeomancer: {
        id: 'option.georefProtocols.biogeomancer',
        defaultMessage: 'BioGeomancer',
      },
    }),
  },
  georefVerificationStatuses: {
    values: [
      'unverified',
      'verified-data-custodian',
      'verified-contributor',
    ],
    messages: defineMessages({
      unverified: {
        id: 'option.georefVerificationStatuses.unverified',
        defaultMessage: 'unverified',
      },
      'verified-data-custodian': {
        id: 'option.georefVerificationStatuses.verified-data-custodian',
        defaultMessage: 'verified by data custodian',
      },
      'verified-contributor': {
        id: 'option.georefVerificationStatuses.verified-contributor',
        defaultMessage: 'verified by contributor',
      },
    }),
  },
};
